modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="treebark"
version="2.0.0"
displayName="TreeBark+"
credits="TreeBark+ 1.19.2"
displayURL="https://nico44yt.github.io/"
logoFile="logo.png"
authors="Nico_44, Let's Code"

[[dependencies.treebark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"




